title: nzululwazi
description: Ocean of knowledge – Research and reflections on oceanography
baseurl: "" 
url: "https://isgiddy.github.io/nzululwazi"
remote_theme: clayh53/tufte-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
