title: nzululwazi
description: Ocean of knowledge – Research and reflections on oceanography
baseurl: ""
url: "https://yourusername.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
